### PR TITLE
Basic list structure and styling for project

### PR DESCRIPTION
**Pull request by franklinben23**
In this pull request I made the basic structure of the app, it till is not interactive, has all the features required by the guidelines.

### CODE REVIEW

**Comment by omar-labana** [comment]
Hi @franklinben23, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, which has no descriptive representation of the project found in the README, node_modules folder should be removed and added to .gitignore.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by mikethreels** [comment]
Hi Franklin , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] As the previous CR mentioned you are supposed to have a descriptive readme file, you can use [the template](https://github.com/microverseinc/readme-template) provided by Microverse for that
- [ ] And as the previous CR also mentioned the node_modules folder should be in the .gitignore file and not in the repo

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by omar-labana** [comment]
Hi @franklinben23 , 

Excellent work so far! 👌
You have implemented almost all the required features. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [x] Please make sure remove the `node_modules` folder from the other branches AFTER merging this branch.
- [x] I can't run the project following instruction found in the README file since it's missing the start script, currently it has only the build script. Please add the required script to run Webpack in development mode.
- [x] Kindly add the module responsible for updating each task `completed` property.
- [x] The tasks objects in the `tasks` array are missing the `completed` property, kindly add it.
- [x] Please make sure that the files found in `node_modules` are completely ignored by GIT since there is more than 4k+ files changes in this branch.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by franklinben23** [comment]
The file changes in this branch in here come from removing the files in node_modules, just so you know.

**Comment by omar-labana** [comment]
> The file changes in this branch in here come from removing the files in node_modules, just so you know.

If these changes are correctly ignored by .gitignore they won't show up.

**Comment by franklinben23** [comment]
> > The file changes in this branch in here come from removing the files in node_modules, just so you know.
> 
> If these changes are correctly ignored by .gitignore they won't show up.

I understand, but I had to delete them remember, that is how I was taught. 
Screenshot_2021-12-03_19-29-47

I first ran this script : $ git rm -r --cached .
and already had the .gitignore file as you can see, please help me find what's wrong in this case.

**Comment by omar-labana** [comment]
> > > The file changes in this branch in here come from removing the files in node_modules, just so you know.
> > 
> > 
> > If these changes are correctly ignored by .gitignore they won't show up.
> 
> I understand, but I had to delete them remember, that is how I was taught. Screenshot_2021-12-03_19-29-47
> 
> I first ran this script : $ git rm -r --cached . and already had the .gitignore file as you can see, please help me find what's wrong in this case.

well... I am not exactly sure what this command do to the tracking system, but git is still tracking this directory as I mentioned
image

**Comment by franklinben23** [comment]
what do you recommend me to do?

**Comment by omar-labana** [comment]
> what do you recommend me to do?

I'd suggest either troubleshooting this issue (You will learn more) or recreating the repo (easy solution but not recommended)

**Comment by omar-labana** [comment]
Hi @franklinben23, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
